/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Campaign from './model/Campaign';
import CampaignStatus from './model/CampaignStatus';
import Character from './model/Character';
import GameSystem from './model/GameSystem';
import Guild from './model/Guild';
import Item from './model/Item';
import RegistrationRequest from './model/RegistrationRequest';
import Stock from './model/Stock';
import User from './model/User';
import UserRoles from './model/UserRoles';
import CampaignApi from './api/CampaignApi';
import CharacterApi from './api/CharacterApi';
import DiscordApi from './api/DiscordApi';
import RegistrationApi from './api/RegistrationApi';
import UserApi from './api/UserApi';


/**
* West_Marches_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WestMarchesApi = require('index'); // See note below*.
* var xxxSvc = new WestMarchesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WestMarchesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WestMarchesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WestMarchesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Campaign model constructor.
     * @property {module:model/Campaign}
     */
    Campaign,

    /**
     * The CampaignStatus model constructor.
     * @property {module:model/CampaignStatus}
     */
    CampaignStatus,

    /**
     * The Character model constructor.
     * @property {module:model/Character}
     */
    Character,

    /**
     * The GameSystem model constructor.
     * @property {module:model/GameSystem}
     */
    GameSystem,

    /**
     * The Guild model constructor.
     * @property {module:model/Guild}
     */
    Guild,

    /**
     * The Item model constructor.
     * @property {module:model/Item}
     */
    Item,

    /**
     * The RegistrationRequest model constructor.
     * @property {module:model/RegistrationRequest}
     */
    RegistrationRequest,

    /**
     * The Stock model constructor.
     * @property {module:model/Stock}
     */
    Stock,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserRoles model constructor.
     * @property {module:model/UserRoles}
     */
    UserRoles,

    /**
    * The CampaignApi service constructor.
    * @property {module:api/CampaignApi}
    */
    CampaignApi,

    /**
    * The CharacterApi service constructor.
    * @property {module:api/CharacterApi}
    */
    CharacterApi,

    /**
    * The DiscordApi service constructor.
    * @property {module:api/DiscordApi}
    */
    DiscordApi,

    /**
    * The RegistrationApi service constructor.
    * @property {module:api/RegistrationApi}
    */
    RegistrationApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
