/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Campaign;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignApi
 */
@Ignore
public class CampaignApiTest {

    private final CampaignApi api = new CampaignApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCampaignIdGetTest() throws ApiException {
        UUID id = null;
        Campaign response = api.apiCampaignIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCampaignIdPostTest() throws ApiException {
        UUID id = null;
        Campaign campaign = null;
        api.apiCampaignIdPost(id, campaign);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCampaignIdPutTest() throws ApiException {
        UUID id = null;
        Campaign campaign = null;
        Campaign response = api.apiCampaignIdPut(id, campaign);

        // TODO: test validations
    }
    
}
