# coding: utf-8

"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.registration_api import RegistrationApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.registration_api.RegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_registration_post(self):
        """Test case for api_registration_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
