"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.campaign_status import CampaignStatus
from openapi_client.model.game_system import GameSystem
from openapi_client.model.guild import Guild
from openapi_client.model.user import User
globals()['CampaignStatus'] = CampaignStatus
globals()['GameSystem'] = GameSystem
globals()['Guild'] = Guild
globals()['User'] = User
from openapi_client.model.campaign import Campaign


class TestCampaign(unittest.TestCase):
    """Campaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaign(self):
        """Test Campaign"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Campaign()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
