# coding: utf-8

"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.campaign_api import CampaignApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCampaignApi(unittest.TestCase):
    """CampaignApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.campaign_api.CampaignApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_campaign_get(self):
        """Test case for api_campaign_get

        """
        pass

    def test_api_campaign_id_get(self):
        """Test case for api_campaign_id_get

        """
        pass

    def test_api_campaign_post(self):
        """Test case for api_campaign_post

        """
        pass

    def test_api_campaign_put(self):
        """Test case for api_campaign_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
