"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item import Item
globals()['Item'] = Item
from openapi_client.model.stock import Stock


class TestStock(unittest.TestCase):
    """Stock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStock(self):
        """Test Stock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Stock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
