"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.campaign import Campaign
from openapi_client.model.user import User
globals()['Campaign'] = Campaign
globals()['User'] = User
from openapi_client.model.user_roles import UserRoles


class TestUserRoles(unittest.TestCase):
    """UserRoles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRoles(self):
        """Test UserRoles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserRoles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
