"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.campaign import Campaign
globals()['Campaign'] = Campaign
from openapi_client.model.guild import Guild


class TestGuild(unittest.TestCase):
    """Guild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGuild(self):
        """Test Guild"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Guild()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
