"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.campaign import Campaign
from openapi_client.model.stock import Stock
from openapi_client.model.user import User
from openapi_client.model.user_roles import UserRoles
globals()['Campaign'] = Campaign
globals()['Stock'] = Stock
globals()['User'] = User
globals()['UserRoles'] = UserRoles
from openapi_client.model.character import Character


class TestCharacter(unittest.TestCase):
    """Character unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCharacter(self):
        """Test Character"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Character()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
