"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.campaign_status import CampaignStatus


class TestCampaignStatus(unittest.TestCase):
    """CampaignStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaignStatus(self):
        """Test CampaignStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CampaignStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
