# coding: utf-8

"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class Campaign(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'game_system': 'GameSystem',
        'title': 'str',
        'owner': 'User',
        'status': 'CampaignStatus',
        'guild': 'Guild'
    }

    attribute_map = {
        'id': 'id',
        'game_system': 'gameSystem',
        'title': 'title',
        'owner': 'owner',
        'status': 'status',
        'guild': 'guild'
    }

    def __init__(self, id=None, game_system=None, title=None, owner=None, status=None, guild=None, local_vars_configuration=None):  # noqa: E501
        """Campaign - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._game_system = None
        self._title = None
        self._owner = None
        self._status = None
        self._guild = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if game_system is not None:
            self.game_system = game_system
        self.title = title
        if owner is not None:
            self.owner = owner
        if status is not None:
            self.status = status
        if guild is not None:
            self.guild = guild

    @property
    def id(self):
        """Gets the id of this Campaign.  # noqa: E501


        :return: The id of this Campaign.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Campaign.


        :param id: The id of this Campaign.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def game_system(self):
        """Gets the game_system of this Campaign.  # noqa: E501


        :return: The game_system of this Campaign.  # noqa: E501
        :rtype: GameSystem
        """
        return self._game_system

    @game_system.setter
    def game_system(self, game_system):
        """Sets the game_system of this Campaign.


        :param game_system: The game_system of this Campaign.  # noqa: E501
        :type game_system: GameSystem
        """

        self._game_system = game_system

    @property
    def title(self):
        """Gets the title of this Campaign.  # noqa: E501


        :return: The title of this Campaign.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Campaign.


        :param title: The title of this Campaign.  # noqa: E501
        :type title: str
        """
        if self.local_vars_configuration.client_side_validation and title is None:  # noqa: E501
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def owner(self):
        """Gets the owner of this Campaign.  # noqa: E501


        :return: The owner of this Campaign.  # noqa: E501
        :rtype: User
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Campaign.


        :param owner: The owner of this Campaign.  # noqa: E501
        :type owner: User
        """

        self._owner = owner

    @property
    def status(self):
        """Gets the status of this Campaign.  # noqa: E501


        :return: The status of this Campaign.  # noqa: E501
        :rtype: CampaignStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Campaign.


        :param status: The status of this Campaign.  # noqa: E501
        :type status: CampaignStatus
        """

        self._status = status

    @property
    def guild(self):
        """Gets the guild of this Campaign.  # noqa: E501


        :return: The guild of this Campaign.  # noqa: E501
        :rtype: Guild
        """
        return self._guild

    @guild.setter
    def guild(self, guild):
        """Sets the guild of this Campaign.


        :param guild: The guild of this Campaign.  # noqa: E501
        :type guild: Guild
        """

        self._guild = guild

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Campaign):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Campaign):
            return True

        return self.to_dict() != other.to_dict()
