/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Character
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CharacterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Character
        //private Character instance;

        public CharacterTests()
        {
            // TODO uncomment below to create an instance of Character
            //instance = new Character();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Character
        /// </summary>
        [Fact]
        public void CharacterInstanceTest()
        {
            // TODO uncomment below to test "IsType" Character
            //Assert.IsType<Character>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Server'
        /// </summary>
        [Fact]
        public void ServerTest()
        {
            // TODO unit test for the property 'Server'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Experience'
        /// </summary>
        [Fact]
        public void ExperienceTest()
        {
            // TODO unit test for the property 'Experience'
        }
        /// <summary>
        /// Test the property 'ExperienceCap'
        /// </summary>
        [Fact]
        public void ExperienceCapTest()
        {
            // TODO unit test for the property 'ExperienceCap'
        }
        /// <summary>
        /// Test the property 'Alive'
        /// </summary>
        [Fact]
        public void AliveTest()
        {
            // TODO unit test for the property 'Alive'
        }
        /// <summary>
        /// Test the property 'Inventory'
        /// </summary>
        [Fact]
        public void InventoryTest()
        {
            // TODO unit test for the property 'Inventory'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'ReadyDate'
        /// </summary>
        [Fact]
        public void ReadyDateTest()
        {
            // TODO unit test for the property 'ReadyDate'
        }
        /// <summary>
        /// Test the property 'DdBeyond'
        /// </summary>
        [Fact]
        public void DdBeyondTest()
        {
            // TODO unit test for the property 'DdBeyond'
        }

    }

}
