/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GameSystem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GameSystemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GameSystem
        //private GameSystem instance;

        public GameSystemTests()
        {
            // TODO uncomment below to create an instance of GameSystem
            //instance = new GameSystem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GameSystem
        /// </summary>
        [Fact]
        public void GameSystemInstanceTest()
        {
            // TODO uncomment below to test "IsType" GameSystem
            //Assert.IsType<GameSystem>(instance);
        }



    }

}
