/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Item
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Item
        //private Item instance;

        public ItemTests()
        {
            // TODO uncomment below to create an instance of Item
            //instance = new Item();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Item
        /// </summary>
        [Fact]
        public void ItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" Item
            //Assert.IsType<Item>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'HomeBrewOrigin'
        /// </summary>
        [Fact]
        public void HomeBrewOriginTest()
        {
            // TODO unit test for the property 'HomeBrewOrigin'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }
        /// <summary>
        /// Test the property 'CurrencyValue'
        /// </summary>
        [Fact]
        public void CurrencyValueTest()
        {
            // TODO unit test for the property 'CurrencyValue'
        }
        /// <summary>
        /// Test the property 'GameSystem'
        /// </summary>
        [Fact]
        public void GameSystemTest()
        {
            // TODO unit test for the property 'GameSystem'
        }

    }

}
