/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RegistrationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistrationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegistrationRequest
        //private RegistrationRequest instance;

        public RegistrationRequestTests()
        {
            // TODO uncomment below to create an instance of RegistrationRequest
            //instance = new RegistrationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegistrationRequest
        /// </summary>
        [Fact]
        public void RegistrationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegistrationRequest
            //Assert.IsType<RegistrationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DiscordId'
        /// </summary>
        [Fact]
        public void DiscordIdTest()
        {
            // TODO unit test for the property 'DiscordId'
        }
        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Fact]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }
        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Fact]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }
        /// <summary>
        /// Test the property 'DdBeyondIds'
        /// </summary>
        [Fact]
        public void DdBeyondIdsTest()
        {
            // TODO unit test for the property 'DdBeyondIds'
        }

    }

}
