/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Stock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Stock
        //private Stock instance;

        public StockTests()
        {
            // TODO uncomment below to create an instance of Stock
            //instance = new Stock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Stock
        /// </summary>
        [Fact]
        public void StockInstanceTest()
        {
            // TODO uncomment below to test "IsType" Stock
            //Assert.IsType<Stock>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DiscountPercentage'
        /// </summary>
        [Fact]
        public void DiscountPercentageTest()
        {
            // TODO unit test for the property 'DiscountPercentage'
        }
        /// <summary>
        /// Test the property 'DiscountFixed'
        /// </summary>
        [Fact]
        public void DiscountFixedTest()
        {
            // TODO unit test for the property 'DiscountFixed'
        }
        /// <summary>
        /// Test the property 'Unlimited'
        /// </summary>
        [Fact]
        public void UnlimitedTest()
        {
            // TODO unit test for the property 'Unlimited'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
