/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CampaignApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CampaignApiTests : IDisposable
    {
        private CampaignApi instance;

        public CampaignApiTests()
        {
            instance = new CampaignApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CampaignApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CampaignApi
            //Assert.IsType<CampaignApi>(instance);
        }

        /// <summary>
        /// Test ApiCampaignIdGet
        /// </summary>
        [Fact]
        public void ApiCampaignIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.ApiCampaignIdGet(id);
            //Assert.IsType<Campaign>(response);
        }

        /// <summary>
        /// Test ApiCampaignIdPost
        /// </summary>
        [Fact]
        public void ApiCampaignIdPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Campaign campaign = null;
            //instance.ApiCampaignIdPost(id, campaign);
        }

        /// <summary>
        /// Test ApiCampaignIdPut
        /// </summary>
        [Fact]
        public void ApiCampaignIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Campaign campaign = null;
            //var response = instance.ApiCampaignIdPut(id, campaign);
            //Assert.IsType<Campaign>(response);
        }
    }
}
