/*
 * WestMarches API
 *
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DiscordApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DiscordApiTests : IDisposable
    {
        private DiscordApi instance;

        public DiscordApiTests()
        {
            instance = new DiscordApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscordApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DiscordApi
            //Assert.IsType<DiscordApi>(instance);
        }

        /// <summary>
        /// Test AddStoreToDiscordServer
        /// </summary>
        [Fact]
        public void AddStoreToDiscordServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.AddStoreToDiscordServer(id);
        }

        /// <summary>
        /// Test CloseDiscordServer
        /// </summary>
        [Fact]
        public void CloseDiscordServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.CloseDiscordServer();
        }

        /// <summary>
        /// Test GetIncomingForDiscordServer
        /// </summary>
        [Fact]
        public void GetIncomingForDiscordServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetIncomingForDiscordServer();
            //Assert.IsType<List<Object>>(response);
        }
    }
}
