/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CampaignStatus = 0 | 1;

export const CampaignStatus = {
    NUMBER_0: 0 as CampaignStatus,
    NUMBER_1: 1 as CampaignStatus
};

