/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameSystem = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

export const GameSystem = {
    NUMBER_0: 0 as GameSystem,
    NUMBER_1: 1 as GameSystem,
    NUMBER_2: 2 as GameSystem,
    NUMBER_3: 3 as GameSystem,
    NUMBER_4: 4 as GameSystem,
    NUMBER_5: 5 as GameSystem,
    NUMBER_6: 6 as GameSystem,
    NUMBER_7: 7 as GameSystem,
    NUMBER_8: 8 as GameSystem,
    NUMBER_9: 9 as GameSystem,
    NUMBER_10: 10 as GameSystem,
    NUMBER_11: 11 as GameSystem
};

