/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameSystem } from './gameSystem';
import { Campaign } from './campaign';


export interface Item { 
    id?: string;
    homeBrewOrigin?: Campaign;
    itemName: string;
    currencyValue: number;
    game_System?: GameSystem;
}

