/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Campaign } from './campaign';
import { Character } from './character';
import { UserCredentials } from './userCredentials';


export interface User { 
    id?: string;
    givenName?: string | null;
    familyName?: string | null;
    dateCreated: string;
    characters?: Array<Character> | null;
    credentials?: Array<UserCredentials> | null;
    campaignsOwned?: Array<Campaign> | null;
}

