/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WestMarchesApi);
  }
}(this, function(expect, WestMarchesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WestMarchesApi.Character();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Character', function() {
    it('should create an instance of Character', function() {
      // uncomment below and update the code to test Character
      //var instane = new WestMarchesApi.Character();
      //expect(instance).to.be.a(WestMarchesApi.Character);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property server (base name: "server")', function() {
      // uncomment below and update the code to test the property server
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property level (base name: "level")', function() {
      // uncomment below and update the code to test the property level
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property experience (base name: "experience")', function() {
      // uncomment below and update the code to test the property experience
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property experienceCap (base name: "experienceCap")', function() {
      // uncomment below and update the code to test the property experienceCap
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property alive (base name: "alive")', function() {
      // uncomment below and update the code to test the property alive
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property inventory (base name: "inventory")', function() {
      // uncomment below and update the code to test the property inventory
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property roles (base name: "roles")', function() {
      // uncomment below and update the code to test the property roles
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property readyDate (base name: "readyDate")', function() {
      // uncomment below and update the code to test the property readyDate
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

    it('should have the property ddBeyond (base name: "ddBeyond")', function() {
      // uncomment below and update the code to test the property ddBeyond
      //var instance = new WestMarchesApi.Character();
      //expect(instance).to.be();
    });

  });

}));
