/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WestMarchesApi);
  }
}(this, function(expect, WestMarchesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WestMarchesApi.Item();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Item', function() {
    it('should create an instance of Item', function() {
      // uncomment below and update the code to test Item
      //var instane = new WestMarchesApi.Item();
      //expect(instance).to.be.a(WestMarchesApi.Item);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WestMarchesApi.Item();
      //expect(instance).to.be();
    });

    it('should have the property homeBrewOrigin (base name: "homeBrewOrigin")', function() {
      // uncomment below and update the code to test the property homeBrewOrigin
      //var instance = new WestMarchesApi.Item();
      //expect(instance).to.be();
    });

    it('should have the property itemName (base name: "itemName")', function() {
      // uncomment below and update the code to test the property itemName
      //var instance = new WestMarchesApi.Item();
      //expect(instance).to.be();
    });

    it('should have the property currencyValue (base name: "currencyValue")', function() {
      // uncomment below and update the code to test the property currencyValue
      //var instance = new WestMarchesApi.Item();
      //expect(instance).to.be();
    });

    it('should have the property gameSystem (base name: "game_System")', function() {
      // uncomment below and update the code to test the property gameSystem
      //var instance = new WestMarchesApi.Item();
      //expect(instance).to.be();
    });

  });

}));
