/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WestMarchesApi);
  }
}(this, function(expect, WestMarchesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WestMarchesApi.Stock();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Stock', function() {
    it('should create an instance of Stock', function() {
      // uncomment below and update the code to test Stock
      //var instane = new WestMarchesApi.Stock();
      //expect(instance).to.be.a(WestMarchesApi.Stock);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property discountPercentage (base name: "discountPercentage")', function() {
      // uncomment below and update the code to test the property discountPercentage
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property discountFixed (base name: "discountFixed")', function() {
      // uncomment below and update the code to test the property discountFixed
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property unlimited (base name: "unlimited")', function() {
      // uncomment below and update the code to test the property unlimited
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property item (base name: "item")', function() {
      // uncomment below and update the code to test the property item
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new WestMarchesApi.Stock();
      //expect(instance).to.be();
    });

  });

}));
