/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Campaign_Status
 */
@JsonAdapter(CampaignStatus.Adapter.class)
public enum CampaignStatus {
  
  NUMBER_0(0),
  
  NUMBER_1(1);

  private Integer value;

  CampaignStatus(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CampaignStatus fromValue(Integer value) {
    for (CampaignStatus b : CampaignStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CampaignStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CampaignStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CampaignStatus read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return CampaignStatus.fromValue(value);
    }
  }
}

