/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.client.model.CampaignStatus;
import org.openapitools.client.model.GameSystem;
import org.openapitools.client.model.Guild;
import org.openapitools.client.model.User;

/**
 * Campaign
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-26T11:34:06.333+10:30[Australia/Adelaide]")
public class Campaign {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_GAME_SYSTEM = "gameSystem";
  @SerializedName(SERIALIZED_NAME_GAME_SYSTEM)
  private GameSystem gameSystem;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private User owner;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private CampaignStatus status;

  public static final String SERIALIZED_NAME_GUILD = "guild";
  @SerializedName(SERIALIZED_NAME_GUILD)
  private Guild guild;


  public Campaign id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public Campaign gameSystem(GameSystem gameSystem) {
    
    this.gameSystem = gameSystem;
    return this;
  }

   /**
   * Get gameSystem
   * @return gameSystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GameSystem getGameSystem() {
    return gameSystem;
  }


  public void setGameSystem(GameSystem gameSystem) {
    this.gameSystem = gameSystem;
  }


  public Campaign title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Campaign owner(User owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getOwner() {
    return owner;
  }


  public void setOwner(User owner) {
    this.owner = owner;
  }


  public Campaign status(CampaignStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CampaignStatus getStatus() {
    return status;
  }


  public void setStatus(CampaignStatus status) {
    this.status = status;
  }


  public Campaign guild(Guild guild) {
    
    this.guild = guild;
    return this;
  }

   /**
   * Get guild
   * @return guild
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Guild getGuild() {
    return guild;
  }


  public void setGuild(Guild guild) {
    this.guild = guild;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Campaign campaign = (Campaign) o;
    return Objects.equals(this.id, campaign.id) &&
        Objects.equals(this.gameSystem, campaign.gameSystem) &&
        Objects.equals(this.title, campaign.title) &&
        Objects.equals(this.owner, campaign.owner) &&
        Objects.equals(this.status, campaign.status) &&
        Objects.equals(this.guild, campaign.guild);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, gameSystem, title, owner, status, guild);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Campaign {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    gameSystem: ").append(toIndentedString(gameSystem)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    guild: ").append(toIndentedString(guild)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

