/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RegistrationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-25T17:55:47.969+10:30[Australia/Adelaide]")
public class RegistrationRequest {
  public static final String SERIALIZED_NAME_DISCORD_ID = "discordId";
  @SerializedName(SERIALIZED_NAME_DISCORD_ID)
  private Long discordId;

  public static final String SERIALIZED_NAME_GIVEN_NAME = "givenName";
  @SerializedName(SERIALIZED_NAME_GIVEN_NAME)
  private String givenName;

  public static final String SERIALIZED_NAME_FAMILY_NAME = "familyName";
  @SerializedName(SERIALIZED_NAME_FAMILY_NAME)
  private String familyName;

  public static final String SERIALIZED_NAME_DD_BEYOND_IDS = "ddBeyondIds";
  @SerializedName(SERIALIZED_NAME_DD_BEYOND_IDS)
  private List<Long> ddBeyondIds = null;


  public RegistrationRequest discordId(Long discordId) {
    
    this.discordId = discordId;
    return this;
  }

   /**
   * Get discordId
   * @return discordId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDiscordId() {
    return discordId;
  }


  public void setDiscordId(Long discordId) {
    this.discordId = discordId;
  }


  public RegistrationRequest givenName(String givenName) {
    
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGivenName() {
    return givenName;
  }


  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }


  public RegistrationRequest familyName(String familyName) {
    
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFamilyName() {
    return familyName;
  }


  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }


  public RegistrationRequest ddBeyondIds(List<Long> ddBeyondIds) {
    
    this.ddBeyondIds = ddBeyondIds;
    return this;
  }

  public RegistrationRequest addDdBeyondIdsItem(Long ddBeyondIdsItem) {
    if (this.ddBeyondIds == null) {
      this.ddBeyondIds = new ArrayList<Long>();
    }
    this.ddBeyondIds.add(ddBeyondIdsItem);
    return this;
  }

   /**
   * Get ddBeyondIds
   * @return ddBeyondIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Long> getDdBeyondIds() {
    return ddBeyondIds;
  }


  public void setDdBeyondIds(List<Long> ddBeyondIds) {
    this.ddBeyondIds = ddBeyondIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistrationRequest registrationRequest = (RegistrationRequest) o;
    return Objects.equals(this.discordId, registrationRequest.discordId) &&
        Objects.equals(this.givenName, registrationRequest.givenName) &&
        Objects.equals(this.familyName, registrationRequest.familyName) &&
        Objects.equals(this.ddBeyondIds, registrationRequest.ddBeyondIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discordId, givenName, familyName, ddBeyondIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistrationRequest {\n");
    sb.append("    discordId: ").append(toIndentedString(discordId)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    ddBeyondIds: ").append(toIndentedString(ddBeyondIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

