/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Campaign from './Campaign';
import GameSystem from './GameSystem';

/**
 * The Item model module.
 * @module model/Item
 * @version 1.0.0
 */
class Item {
    /**
     * Constructs a new <code>Item</code>.
     * @alias module:model/Item
     * @param itemName {String} 
     * @param currencyValue {Number} 
     */
    constructor(itemName, currencyValue) { 
        
        Item.initialize(this, itemName, currencyValue);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, itemName, currencyValue) { 
        obj['itemName'] = itemName;
        obj['currencyValue'] = currencyValue;
    }

    /**
     * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Item} obj Optional instance to populate.
     * @return {module:model/Item} The populated <code>Item</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('homeBrewOrigin')) {
                obj['homeBrewOrigin'] = Campaign.constructFromObject(data['homeBrewOrigin']);
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('currencyValue')) {
                obj['currencyValue'] = ApiClient.convertToType(data['currencyValue'], 'Number');
            }
            if (data.hasOwnProperty('game_System')) {
                obj['game_System'] = GameSystem.constructFromObject(data['game_System']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Item.prototype['id'] = undefined;

/**
 * @member {module:model/Campaign} homeBrewOrigin
 */
Item.prototype['homeBrewOrigin'] = undefined;

/**
 * @member {String} itemName
 */
Item.prototype['itemName'] = undefined;

/**
 * @member {Number} currencyValue
 */
Item.prototype['currencyValue'] = undefined;

/**
 * @member {module:model/GameSystem} game_System
 */
Item.prototype['game_System'] = undefined;






export default Item;

