/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegistrationRequest model module.
 * @module model/RegistrationRequest
 * @version 1.0.0
 */
class RegistrationRequest {
    /**
     * Constructs a new <code>RegistrationRequest</code>.
     * @alias module:model/RegistrationRequest
     */
    constructor() { 
        
        RegistrationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegistrationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistrationRequest} obj Optional instance to populate.
     * @return {module:model/RegistrationRequest} The populated <code>RegistrationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistrationRequest();

            if (data.hasOwnProperty('discordId')) {
                obj['discordId'] = ApiClient.convertToType(data['discordId'], 'Number');
            }
            if (data.hasOwnProperty('givenName')) {
                obj['givenName'] = ApiClient.convertToType(data['givenName'], 'String');
            }
            if (data.hasOwnProperty('familyName')) {
                obj['familyName'] = ApiClient.convertToType(data['familyName'], 'String');
            }
            if (data.hasOwnProperty('ddBeyondIds')) {
                obj['ddBeyondIds'] = ApiClient.convertToType(data['ddBeyondIds'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} discordId
 */
RegistrationRequest.prototype['discordId'] = undefined;

/**
 * @member {String} givenName
 */
RegistrationRequest.prototype['givenName'] = undefined;

/**
 * @member {String} familyName
 */
RegistrationRequest.prototype['familyName'] = undefined;

/**
 * @member {Array.<Number>} ddBeyondIds
 */
RegistrationRequest.prototype['ddBeyondIds'] = undefined;






export default RegistrationRequest;

