/**
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Campaign from './Campaign';
import Character from './Character';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param dateCreated {Date} 
     */
    constructor(dateCreated) { 
        
        User.initialize(this, dateCreated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dateCreated) { 
        obj['dateCreated'] = dateCreated;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('discordId')) {
                obj['discordId'] = ApiClient.convertToType(data['discordId'], 'Number');
            }
            if (data.hasOwnProperty('givenName')) {
                obj['givenName'] = ApiClient.convertToType(data['givenName'], 'String');
            }
            if (data.hasOwnProperty('familyName')) {
                obj['familyName'] = ApiClient.convertToType(data['familyName'], 'String');
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('characters')) {
                obj['characters'] = ApiClient.convertToType(data['characters'], [Character]);
            }
            if (data.hasOwnProperty('campaignsOwned')) {
                obj['campaignsOwned'] = ApiClient.convertToType(data['campaignsOwned'], [Campaign]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
User.prototype['id'] = undefined;

/**
 * @member {Number} discordId
 */
User.prototype['discordId'] = undefined;

/**
 * @member {String} givenName
 */
User.prototype['givenName'] = undefined;

/**
 * @member {String} familyName
 */
User.prototype['familyName'] = undefined;

/**
 * @member {Date} dateCreated
 */
User.prototype['dateCreated'] = undefined;

/**
 * @member {Array.<module:model/Character>} characters
 */
User.prototype['characters'] = undefined;

/**
 * @member {Array.<module:model/Campaign>} campaignsOwned
 */
User.prototype['campaignsOwned'] = undefined;






export default User;

