# coding: utf-8

# flake8: noqa

"""
    WestMarches API

    West Marches API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.campaign_api import CampaignApi
from openapi_client.api.character_api import CharacterApi
from openapi_client.api.discord_api import DiscordApi
from openapi_client.api.registration_api import RegistrationApi
from openapi_client.api.user_api import UserApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.campaign import Campaign
from openapi_client.models.campaign_status import CampaignStatus
from openapi_client.models.character import Character
from openapi_client.models.game_system import GameSystem
from openapi_client.models.guild import Guild
from openapi_client.models.item import Item
from openapi_client.models.stock import Stock
from openapi_client.models.user import User
from openapi_client.models.user_credentials import UserCredentials
from openapi_client.models.user_roles import UserRoles

