/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CampaignStatus
 */
public class CampaignStatusTest {
    /**
     * Model tests for CampaignStatus
     */
    @Test
    public void testCampaignStatus() {
        // TODO: test CampaignStatus
    }

}
