/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Campaign;
import org.openapitools.client.model.Stock;
import org.openapitools.client.model.User;
import org.openapitools.client.model.UserRoles;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Character
 */
public class CharacterTest {
    private final Character model = new Character();

    /**
     * Model tests for Character
     */
    @Test
    public void testCharacter() {
        // TODO: test Character
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'server'
     */
    @Test
    public void serverTest() {
        // TODO: test server
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'experience'
     */
    @Test
    public void experienceTest() {
        // TODO: test experience
    }

    /**
     * Test the property 'experienceCap'
     */
    @Test
    public void experienceCapTest() {
        // TODO: test experienceCap
    }

    /**
     * Test the property 'alive'
     */
    @Test
    public void aliveTest() {
        // TODO: test alive
    }

    /**
     * Test the property 'inventory'
     */
    @Test
    public void inventoryTest() {
        // TODO: test inventory
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'readyDate'
     */
    @Test
    public void readyDateTest() {
        // TODO: test readyDate
    }

    /**
     * Test the property 'ddBeyond'
     */
    @Test
    public void ddBeyondTest() {
        // TODO: test ddBeyond
    }

}
