/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Campaign;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Guild
 */
public class GuildTest {
    private final Guild model = new Guild();

    /**
     * Model tests for Guild
     */
    @Test
    public void testGuild() {
        // TODO: test Guild
    }

    /**
     * Test the property 'campaign'
     */
    @Test
    public void campaignTest() {
        // TODO: test campaign
    }

    /**
     * Test the property 'discordId'
     */
    @Test
    public void discordIdTest() {
        // TODO: test discordId
    }

    /**
     * Test the property 'guildName'
     */
    @Test
    public void guildNameTest() {
        // TODO: test guildName
    }

    /**
     * Test the property 'storeCategoryName'
     */
    @Test
    public void storeCategoryNameTest() {
        // TODO: test storeCategoryName
    }

}
