/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.client.model.Campaign;
import org.openapitools.client.model.GameSystem;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Item
 */
public class ItemTest {
    private final Item model = new Item();

    /**
     * Model tests for Item
     */
    @Test
    public void testItem() {
        // TODO: test Item
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'homeBrewOrigin'
     */
    @Test
    public void homeBrewOriginTest() {
        // TODO: test homeBrewOrigin
    }

    /**
     * Test the property 'itemName'
     */
    @Test
    public void itemNameTest() {
        // TODO: test itemName
    }

    /**
     * Test the property 'currencyValue'
     */
    @Test
    public void currencyValueTest() {
        // TODO: test currencyValue
    }

    /**
     * Test the property 'gameSystem'
     */
    @Test
    public void gameSystemTest() {
        // TODO: test gameSystem
    }

}
