/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RegistrationRequest
 */
public class RegistrationRequestTest {
    private final RegistrationRequest model = new RegistrationRequest();

    /**
     * Model tests for RegistrationRequest
     */
    @Test
    public void testRegistrationRequest() {
        // TODO: test RegistrationRequest
    }

    /**
     * Test the property 'discordId'
     */
    @Test
    public void discordIdTest() {
        // TODO: test discordId
    }

    /**
     * Test the property 'givenName'
     */
    @Test
    public void givenNameTest() {
        // TODO: test givenName
    }

    /**
     * Test the property 'familyName'
     */
    @Test
    public void familyNameTest() {
        // TODO: test familyName
    }

    /**
     * Test the property 'ddBeyondIds'
     */
    @Test
    public void ddBeyondIdsTest() {
        // TODO: test ddBeyondIds
    }

}
