/*
 * WestMarches API
 * West Marches API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.client.model.Item;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Stock
 */
public class StockTest {
    private final Stock model = new Stock();

    /**
     * Model tests for Stock
     */
    @Test
    public void testStock() {
        // TODO: test Stock
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'discountPercentage'
     */
    @Test
    public void discountPercentageTest() {
        // TODO: test discountPercentage
    }

    /**
     * Test the property 'discountFixed'
     */
    @Test
    public void discountFixedTest() {
        // TODO: test discountFixed
    }

    /**
     * Test the property 'unlimited'
     */
    @Test
    public void unlimitedTest() {
        // TODO: test unlimited
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'item'
     */
    @Test
    public void itemTest() {
        // TODO: test item
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

}
