name: deploy

on:
  push:
    branches:
      - master

   Javascript:
     needs: Deploy
     runs-on: ubuntu-latest
     steps:
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
         registry-url: 'https://npm.pkg.github.com'
     - name: install
       run: |
         npm install -g @openapitools/openapi-generator-cli
         openapi-generator-cli version-manager set 4.3.1
         openapi-generator-cli version
     - name: generate
       run: |
         npx @openapitools/openapi-generator-cli generate -i swagger.json -g javascript -o js
     - name: install and publish
       run: |
         cd js
         npm install
         npm publish
