name: deploy

on:
  push:
    branches:
      - master

jobs:
  Javascript:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
         registry-url: 'https://npm.pkg.github.com'
     - name: install
       run: |
         npm install -g @openapitools/openapi-generator-cli
         openapi-generator-cli version-manager set 4.3.1
         openapi-generator-cli version
     - name: generate
       run: |
         npx @openapitools/openapi-generator-cli generate -i swagger.json -g javascript -o javascript
     - name: install and publish
       run: |
         cd javascript
         cat ./package.json | jq '.scripts.prepack = ["npm install && npm run build"]' > ./package1.json
         cat ./package1.json | jq '.scripts.prepack = ["npm install && npm run build"]' > ./package.json
         npm install
         npm publish
       env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
