name: deploy

on:
  push:
    branches:
      - master

jobs:
  Javascript:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
         registry-url: 'https://npm.pkg.github.com'
     - name: install
       run: |
         npm install -g @openapitools/openapi-generator-cli
         openapi-generator-cli version-manager set 4.3.1
         openapi-generator-cli version
     - name: generate
       run: |
         npx @openapitools/openapi-generator-cli generate -i swagger.json -g javascript -o javascript
     - name: install and publish
       run: |
         cd javascript
         cat ./package.json | jq '.scripts.prepack = ["npm install && npm run build"]' > ./package1.json
         cat ./package1.json | jq '.scripts.prepack = ["npm install && npm run build"]' > ./package.json
         npm install
         npm login --registry=https://npm.pkg.github.com
         npm publish
       env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

  C-Sharp:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 3.1.100
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
         registry-url: 'https://npm.pkg.github.com'
     - name: install
       run: |
         npm install -g @openapitools/openapi-generator-cli
         openapi-generator-cli version-manager set 4.3.1
         openapi-generator-cli version
     - name: generate
       run: |
         npx @openapitools/openapi-generator-cli generate -i swagger.json -g csharp-netcore -o csharp-netcore -targetFramework netcoreapp3.1
     - name: install and publish
       run: |
         cd csharp-netcore
         ls
     - name: Pack with dotnet
       run: dotnet pack  --configuration Release
     - uses: nuget/setup-nuget@v1
       with:
         nuget-api-key: ${{ secrets.NUGET_API_KEY }}
         nuget-version: 'latest'
#     - name: Push package to the Github Package Registry
#       run: |
#         nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/WestMarches/index.json" -UserName WestMarches -Password ${{ secrets.GITHUB_TOKEN }}
#         nuget setApiKey ${{ secrets.NUGET_API_KEY }} -Source "GPR"
#         nuget push WM-SDK/bin/Release/*.nupkg -Source "GPR" -SkipDuplicate
